---
title: "R Notebook"
#output: html_notebook
author: "Val Syverson"
---
```{r}
require(leaflet)
require(sf); require(terra)
require(here); require(dplyr)
require(neotoma2)
```

Download site locations and combine with dates table.
```{r}
if (!exists("alldates")) alldates <- read.csv(here("workflow/data/alldates.csv"))
if (!exists("geochrons")) geochrons <- read.csv(here("workflow/data/dates_for_analysis_smallmamm.csv"))
if (!exists("newchron.range")) newchron.range <- read.csv(here("workflow/outputs/new_chronologies.csv"))
if (!exists("found")) found <- read.csv(here("dates_revision/found.csv"))

siteids <- unique(alldates$siteid)
sitelist <- get_sites(siteids, all_data = T)
sites <- as.data.frame(sitelist)
sites <- inner_join(sites,getids(sitelist))
sites <- distinct(sites[,-which(colnames(sites) == "datasetid")])
sites <- subset(sites,sites$collunitid %in% newchron.range$collectionunitid)
```

Tag the collections for which we added new dates.
```{r}
sites$newdates <- NA
sites[which(!sites$siteid %in% unique(geochrons$siteid)),"newdates"] <- "all"
sites[which(!sites$siteid %in% unique(setdiff(alldates[,1:19],geochrons)$siteid)),"newdates"] <- "none"
sites[which(sites$siteid %in% unique(setdiff(alldates[,1:19],geochrons)$siteid) & 
                            sites$siteid %in% unique(geochrons$siteid)),"newdates"] <- "some"
sites$newdates <- factor(sites$newdates,levels = c("none","some","all"))
sites <- sites[order(sites$newdates),]
```

Add the age ranges from our new chronologies.
```{r}
sites$agemax <- newchron.range[match(sites$collunitid,subset(newchron.range,newchron.range$agemodel == "event")$collectionunitid),"ageboundolder"]
sites$agemin <- newchron.range[match(sites$collunitid,subset(newchron.range,newchron.range$agemodel == "event")$collectionunitid),"ageboundyounger"]
```

Plot of date locations distinguishing update status; table showing sources of new dates
```{r}
require(maps); require(rnaturalearth); require(oce)

epsg9311 <- leafletCRS(
  crsClass = "L.Proj.CRS",
  code = "EPSG:9311",
  proj4def = "+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +a=6370997 +b=6370997 +units=m +no_defs",
  resolutions = 2 ^ (16:7),
  origin = c(0,0)
)

north_america <-
  rnaturalearth::countries110 |>
  dplyr::filter(CONTINENT == "North America")

pal <- colorFactor("RdGy",sites$newdates,reverse = T)

mapPlot(coastlineWorld,
        col = "lightgray",
        projection = "+proj=laea +lat_0=45 +lon_0=-100 +x_0=0 +y_0=0 +a=6370997 +b=6370997 +units=m +no_defs",
        longitudelim = xlims, latitudelim = ylims)

```


```{r Figure 4a}
leaflet(north_america, options = leafletOptions(crs = epsg9311)) %>%
  addPolygons(weight=1,color="grey70",opacity = 0.8) %>%
  addCircleMarkers(data=sites[,c("long","lat")],
                   color = ~pal(sites$newdates),fillColor = ~pal(sites$newdates),
                   radius = 2,stroke = T,fillOpacity = 0.9) %>%
  addLegend(position = "bottomleft", pal = pal, values = levels(sites$newdates),
            title = "New dates by site")
```


```{r Figure 4b old version}
require(ggplot2)
temp <- cut(as.numeric(found$ndb.geochronology.age),c(0,6000,11700,16000,60000)) 
levels(temp) <- c("Late Hol.","Early Hol.","Deglacial","LGM")
temp <- data.frame(table(temp),"")
colnames(temp) <- c("Interval","Number","Dates")
ggplot(temp,aes(x = Dates,y = Number,fill = Interval)) + geom_col() + scale_fill_brewer(palette = "Blues")
```

```{r}
require(ggplot2); require(sf)
crdref <- "+proj=longlat +datum=WGS84"
sites <- as.data.frame(sitelist)[,c("lat","long","siteid","sitename")]
sites$siteid <- as.numeric(sites$siteid)
sites.vect <- vect(sites[c("long","lat")],geom = c("long","lat"),crs = crdref)
dates <- inner_join(alldates[,c("siteid","geochronid","age","errorolder")],sites)
dates$interval <- cut(as.numeric(dates$age),c(0,6000,11700,16000,60000))
levels(dates$interval) <- c("Late Hol.","Early Hol.","Deglacial","LGM")
dates$new <- as.factor(dates$source);  levels(dates$new) <- c("TRUE","TRUE","FALSE","TRUE"); dates$new <- as.factor(as.character(dates$new))
```


```{r Figure 4c}
temp <- subset(dates,dates$new == TRUE)
dates.vect <- sapply(split(temp,temp$interval), 
                     function(x) vect(x[,c("long","lat")],geom = c("long","lat"),crs = crdref))
eco1 <- read_sf("/mnt/chromeos/MyFiles/Downloads/na_cec_eco_l1/NA_CEC_Eco_Level1.shp")
eco1 <- st_transform(eco1,st_crs("+proj=longlat +datum=WGS84"))
temp <- sapply(dates.vect,function(x) relate(vect(eco1), x, "contains"))
datecount <- sapply(temp, function(x) apply(x,1,sum))
```


```{r print Figure 4c}
temp <- data.frame(eco1$NA_L1NAME,datecount);colnames(temp) <- c("Ecozone","LH","EH","DG","LGM")
temp <- do.call("rbind",by(temp,temp$Ecozone,function(x) apply(x[,2:5],2,function(x) sum(x))))
datecounts <- data.frame(Ecozone = rownames(temp), temp[,4:1])
datecounts$Ecozone <- gsub("NORTHWESTERN","NW",datecounts$Ecozone)
datecounts$Ecozone <- reorder(datecounts$Ecozone,apply(datecounts[,2:5],1,sum),decreasing = T)
datecounts <- datecounts[order(apply(datecounts[,2:5],1,sum),decreasing = T),][1:12,]
temp <- reshape::melt(datecounts);colnames(temp) <- c("Ecozone","Interval","Count")
ggplot(temp,aes(x = Interval,y = Count,fill = Ecozone)) + geom_bar(stat = "identity") + scale_fill_brewer(palette = "Paired")
```

```{r}
dates.vect <- sapply(split(dates,dates$interval), 
                     function(x) vect(x[,c("long","lat")],geom = c("long","lat"),crs = crdref))
eco1 <- read_sf("/mnt/chromeos/MyFiles/Downloads/na_cec_eco_l1/NA_CEC_Eco_Level1.shp")
eco1 <- st_transform(eco1,st_crs("+proj=longlat +datum=WGS84"))
temp <- sapply(dates.vect,function(x) relate(vect(eco1), x, "contains"))
alldatecount <- sapply(temp, function(x) apply(x,1,sum))
temp <- data.frame(eco1$NA_L1NAME,alldatecount);colnames(temp) <- c("Ecozone","LH","EH","DG","LGM")
temp <- do.call("rbind",by(temp,temp$Ecozone,function(x) apply(x[,2:5],2,function(x) sum(x))))
alldatecounts <- data.frame(Ecozone = rownames(temp), temp[,4:1])
alldatecounts$Ecozone <- gsub("NORTHWESTERN","NW",alldatecounts$Ecozone)
alldatecounts$Ecozone <- reorder(alldatecounts$Ecozone,apply(alldatecounts[,2:5],1,sum),decreasing = T)
alldatecounts <- alldatecounts[order(apply(alldatecounts[,2:5],1,sum),decreasing = T),][1:12,]
temp <- data.frame(rbind(data.frame(datecounts,Group = "New"),data.frame(alldatecounts,Group = "All")))
temp <- reshape::melt(temp);colnames(temp) <- c("Ecozone","Group","Interval","Count")
temp <- split(temp,temp$Group)
```


```{r}
require(ggplot2)
allp <- ggplot(temp$All,aes(x = Interval,y = Count,fill = Ecozone)) + geom_bar(stat = "identity") + scale_fill_brewer(palette = "Paired") + guides(fill = "none") + ggtitle("All dates")
newp <- ggplot(temp$New,aes(x = Interval,y = Count,fill = Ecozone)) + geom_bar(stat = "identity") + scale_fill_brewer(palette = "Paired") + guides(fill = "none") + ggtitle("New dates")
leg <- cowplot::get_legend(ggplot(temp$New,aes(x = Interval,y = Count,fill = Ecozone)) + geom_bar(stat = "identity") + scale_fill_brewer(palette = "Paired"))
gridExtra::grid.arrange(allp,newp,leg,ncol = 3,nrow = 1)
```

```{r Figure 5}
#range plot of age bounds
if (!exists("newchron.all")) newchron.all <- read.csv("../../outputs/new_sampleages.csv")
test <- subset(newchron.all,newchron.all$chronology.agemodel == "bounds")[,c("sampleages.ageolder","sampleages.ageyounger")]
test <- test[order(test$sampleages.ageolder),]
test <- test[-which(test$sampleages.ageolder == max(test$sampleages.ageolder)),] #drop outlier site
ggplot(test, aes(y = 1:nrow(test))) +
  geom_linerange(aes(xmin = sampleages.ageyounger, xmax = sampleages.ageolder),
                 size = 1.5, alpha = 0.25) +
  scale_x_reverse() +
  geom_point(aes(x = sampleages.ageolder), color = "blue", size = 0.5) +
  geom_point(aes(x = sampleages.ageyounger), color = "red", size = 0.5) +
  geom_vline(xintercept = 11700)
```

